export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  operations: '/operations',
  bookings: '/bookings',
  createBooking: '/create-booking',
  live: '/live',
  drivers: '/drivers',
  riders: '/riders',
  applications: '/applications',
  reports: '/reports',
  trips: '/trips',
  schedule: '/schedule',
  coverage: '/coverage',
  settings: '/settings',
  profile: '/profile',
  fleet: '/fleet',
  fleetDetails: (id: string) => `/fleet/${id}`,
  notifications: '/notifications',
  transactions: '/finance',
  staff: '/staff',
  cms: '/cms',
  support: '/support',
  push: '/push',
} as const;
